name: Lint Code

on:
  push:
    branches:
      - main
      - develop
      - feature/linter
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8  # Install Flake8

      - name: Get changed files
        id: get_changed_files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' | tr '\n' ' ')"

      - name: Run Pylint
        run: |
          if [ -n "${{ steps.get_changed_files.outputs.files }}" ]; then
            pylint ${{ steps.get_changed_files.outputs.files }}
          else
            echo "No Python files changed."
          fi