name: Lint Code

on:
  push:
    branches:
      - main
      - develop
      - feature/linter
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Runing Pylint
        run: |
          find . -name '*.py' -exec pylint --fail-under=8.5 {} \;
